name: Create YouTube Plus tvOS app

on:
  workflow_dispatch:
    inputs:
      enable_youpip:
        description: "Integrate YouPiP"
        type: boolean
        required: true
        default: false

      enable_ytuhd:
        description: "Integrate YTUHD"
        type: boolean
        required: true
        default: false

      enable_ryd:
        description: "Integrate Return YouTube Dislikes"
        type: boolean
        required: true
        default: false

      enable_yq:
        description: "Integrate YouQuality"
        type: boolean
        required: true
        default: false

      enable_demc:
        description: "Integrate DontEatMyContent"
        type: boolean
        required: true
        default: false

      ipa_url:
        description: "URL to the decrypted tvOS IPA file"
        default: ""
        required: true
        type: string

      tweak_version:
        description: "Version of YTLite to use"
        default: "5.2b1"
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build tvOS YouTubePlus
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Validate IPA URL
        run: |
          curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
          file_type=$(file --mime-type -b sample.part)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
            exit 1
          fi

      - name: Install Dependencies
        run: brew install make ldid wget

      - name: Set PATH
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4
        env:
          cache-name: theos_cache_appletv
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: 67db2ab8d950910161730de77c322658ea3e6b44
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Download and extract AppleTVOS12.4.sdk
        if: steps.theos.outputs.cache-hit != 'true'
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          wget --content-disposition https://github.com/theos/sdks/releases/download/master-146e41f/AppleTVOS12.4.sdk.tar.xz
          mkdir -p "$THEOS/sdks"
          tar -xvf AppleTVOS12.4.sdk.tar.xz -C "$THEOS/sdks"

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download YouTube Plus
        run: |
          wget "https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.tweak_version }}/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb" \
            --no-verbose -O ${{ github.workspace }}/ytplus.deb

      - name: Download YouTube
        run: |
          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa

      - name: Clone YouTubeHeader
        run: |
          cd ${{ github.workspace }}/theos/include
          if [ -d "YouTubeHeader" ]; then
            cd YouTubeHeader && git pull
          else
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi

      - name: Clone PSHeader
        run: |
          cd ${{ github.workspace }}/theos/include
          if [ -d "PSHeader" ]; then
            cd PSHeader && git pull
          else
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi

      - name: Clone and Build Tweaks
        run: |
          set -e
          cd ${{ github.workspace }}

          clone_and_build() {
            local repo=$1
            local dir=$2
            git clone --quiet --depth=1 $repo $dir
            cd $dir
            make clean package DEBUG=0 FINALPACKAGE=1 || echo "⚠️ Build failed for $dir"
            mv packages/*.deb ../${dir}.deb || true
            cd ..
          }

          if [[ "${{ inputs.enable_youpip }}" == "true" ]]; then
            clone_and_build https://github.com/PoomSmart/YouPiP.git YouPiP
          fi

          if [[ "${{ inputs.enable_ytuhd }}" == "true" ]]; then
            clone_and_build https://github.com/PoomSmart/YTUHD.git YTUHD
          fi

          if [[ "${{ inputs.enable_ryd }}" == "true" ]]; then
            clone_and_build https://github.com/PoomSmart/Return-YouTube-Dislikes.git Return-YouTube-Dislikes
          fi

          if [[ "${{ inputs.enable_yq }}" == "true" ]]; then
            clone_and_build https://github.com/PoomSmart/YouQuality.git YouQuality
            clone_and_build https://github.com/PoomSmart/YTVideoOverlay.git YTVideoOverlay
          fi

          if [[ "${{ inputs.enable_demc }}" == "true" ]]; then
            clone_and_build https://github.com/PoomSmart/YouGroupSettings.git YouGroupSettings
            clone_and_build https://github.com/therealFoxster/DontEatMyContent.git DontEatMyContent
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Inject tweaks into IPA
        run: |
          set -e
          tweaks="ytplus.deb"
          for deb in youpip ytuhd ryd ygs yq ytvo demc; do
            [ -f "$deb.deb" ] && tweaks="$tweaks $deb.deb"
          done

          if [ ! -f youtube.ipa ]; then
            echo "::error::Missing youtube.ipa"
            exit 1
          fi

          cyan -i youtube.ipa -o YouTubePlus_${{ inputs.tweak_version }}.ipa -uwef $tweaks \
            -n "${{ inputs.display_name }}" -b "${{ inputs.bundle_id }}"

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          name: YouTubePlus tvOS v${{ inputs.tweak_version }} (${{ github.run_number }})
          files: YouTubePlus_${{ inputs.tweak_version }}.ipa
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"

      - name: Cleanup
        run: rm -f *.deb *.tar.xz sample.part
